### ISSUE TITLE
Update to use the WP REST API

### ISSUE THREAD

**Issue by ideadude** [strangerstudios/pmpro-zapier#16]
Instead of using a URL like /?pmpro_zapier_webhook=1&api_key=...

We should use the WP REST API. We can create an route /pmpro_zapier/v1/ and then add endpoints for members and orders.

So URLs would look like:

/pmpro_zapier/v1/orders/add/?code=...&api_key=...
/pmpro_zapier/v1/orders/{order_id}/update/?code=&api_key=...
/pmpro_zapier/v1/members/add/?user_email=...&level_id=...&api_key=...
/pmpro_zapier/v1/members/{user_id or user_email or user_login}/change_membership_level/...
/pmpro_zapier/v1/members/{user_id or user_email or user_login}/has_membership/...

This would basically mirror the REST API for PMPro in general. You could actually use the PMPro REST API instead, but I think it's a good idea to copy it in this plugin as well to make it easier for people to setup/etc.

**Comment by andrewlimaza** [comment]
Closing this as we've released our Zapier Application (native) integration - https://www.paidmembershipspro.com/documentation/compatibility/zapier/
