### ISSUE TITLE
Support usermeta

### ISSUE THREAD

**Issue by andrewlimaza** [strangerstudios/pmpro-zapier#17]
A request has come in to store some additional fields as user meta.

**Comment by eighty20results** [comment]
Could you share the list of fields?

**Comment by andrewlimaza** [comment]
The user hasn't specified a list of fields they would like to store. Maybe if we had a hook and loop through what the user defines from within the hook and tries to store it as usermeta/options could be nifty in some cases such as the `add_member` action?

**Comment by andrewlimaza** [comment]
To update this, @ideadude and I spoke about it briefly.

We could possibly use a format of `um_text_metakey` or `um_int_metakey` and loop through this data received and insert it into user meta.

**Comment by andrewlimaza** [comment]
We have just added in filters to allow users to insert their own fields when posting data to Zapier.
