### ISSUE TITLE
Pull in user data on credit card transactions

### ISSUE THREAD

**Issue by Veshil** [strangerstudios/pmpro-zapier#21]
Hi,

At the moment, if a member pays for their membership by credit card, almost no data gets imported to zapier.  See below image what gets imported. If they pay by check/bank transfer, I get all the data and can continue the zap through to my accounting software.

![image](https://user-images.githubusercontent.com/33862871/42033450-7fd468ec-7b0f-11e8-9748-762e78d87ba0.png)

Regards,
Veshil

**Comment by andrewlimaza** [comment]
Thanks Veshil, what payment gateway are you using to accept the credit card payments on Paid Memberships Pro?

Please can you open one thread per issue so we may run relative tests per issue and so they don't get lost within a different issue like this one? :)

Thank you for your understanding.

**Comment by Veshil** [comment]
I'm using stripe. Yeah I'll open another one for the importing issue.

Veshil
________________________________

**Comment by andrewlimaza** [comment]
Thanks for this Veshil, we are working on fixing this and it's a known bug now.

I'm really sorry for any inconvenience caused.

**Comment by andrewlimaza** [comment]
I will close this thread as there is a duplicate issue regarding this - https://github.com/strangerstudios/pmpro-zapier/issues/39
