### ISSUE TITLE
How do you use the Actions?

### ISSUE THREAD

**Issue by sunnyt7** [strangerstudios/pmpro-zapier#27]
We need better documentation for the "Receive data from Zapier (Actions)." For example, how do I use the add_member action? Does it go in the URL somewhere?

**Comment by andrewlimaza** [comment]
We are working on improving this documentation for this particular action.

Here's the gist of it:

1. Setup a trigger from the application you want to send data from, in your case Google Sheets (New row added).
2. Setup an action (Webhooks by Zapier) and Select “POST” as the type of request.
3. You should be on the ‘Edit Template’ step, I will walk through each setting that is required for the Zap to work:

3.1 URL – paste in the webhook URL from the PMPro Zapier -> Receive Data From Zapier tab. Please include the full URL (it includes the API key and trigger for the webhook in WordPress – this is what works as authentication).

3.2 Payload Type – Set this to “Form”

3.3 Under “Data” this is where all the data you want to push to WordPress and includes the required data for each action (i.e. add_member etc.). Here is a screenshot for reference:

<img width="780" alt="zapier" src="https://user-images.githubusercontent.com/12629136/43826807-84e9c74c-9af8-11e8-8725-1f7d8a4b2a2a.png">

3.4 Wrap Request in Array – Set this to “No”

3.5 Unflatten – Set this to “No”

4. Press “Continue” to test your webhook.

You do not need to add any other information besides the steps above. I hope this help

**Comment by sunnyt7** [comment]
Ah jeez, that helps immensely! Thank you!

And then as an example, let's say I wanted to add or update members whenever they get added to a specific ActiveCampaign list... would you recommend I use the add_member or change_membership_level action? Or do you use both?

**Comment by andrewlimaza** [comment]
I think you could use add_member in this case if you want to add in a new member. change_membership_level would be to adjust an existing user.

**Comment by andrewlimaza** [comment]
For higher-level support, please open a ticket on www.paidmembershipspro.com.
