### ISSUE TITLE
Filters to allow adjustment of data sent to Zapier

### ISSUE THREAD

**Issue by andrewlimaza** [strangerstudios/pmpro-zapier#30]
A user would like to send custom fields when sending data to Zapier, we should add in filters for this.

**Comment by adishaked** [comment]
hi 
how can i send a custom fields data to zapier
the extra fields do not show on zapier

thank you

**Comment by andrewlimaza** [comment]
We are still working on a solution for this and currently you would need to adjust the plugin's code directly (which is not recommended).

Depending on what trigger you're using inside Paid Memberships Pro, you may edit here and adjust the $data array to include additional fields - https://github.com/strangerstudios/pmpro-zapier/blob/master/includes/class-pmpro-zapier.php#L182

**Comment by andrewlimaza** [comment]
Merged.
