### ISSUE TITLE
Feature Request: Option to send WP New User Notification

### ISSUE THREAD

**Issue by messica** [strangerstudios/pmpro-zapier#33]
We should add the option to send new user notifications from PMPro Zapier, or at least add a hook after the user is created.

**Support Ticket (Moderators Only)**
https://www.paidmembershipspro.com/forums/topic/send-user-details-when-order-is-placed-via-zapier-hook/

**Comment by andrewlimaza** [comment]
I've got a PR waiting for being merged, going to revisit this to improve on it :). Should be released in next version.

**Comment by andrewlimaza** [comment]
This has been merged in.
