### ISSUE TITLE
Username and email not passing through to Zapier

### ISSUE THREAD

**Issue by Stijnp** [strangerstudios/pmpro-zapier#39]
I am testing the plugin but can't seem to get the username and email address in Zapier. It always shows empty. I have real subscriptions and dummy data. None of the attempts succeeded. (I have the billing address fields not showing.)

<img width="322" alt="Screen Shot 2019-05-06 at 7 14 02 pm" src="https://user-images.githubusercontent.com/10431367/57217225-5dc0ba00-7035-11e9-8558-3a8ea47dc201.png">

**Comment by Stijnp** [comment]
The issue is resolved when I also link the Updated Order to my webhook.

**Comment by andrewlimaza** [comment]
Hey @Stijnp 

Which hook did you use to create the issue? Was it on membership change?

**Comment by andrewlimaza** [comment]
I'll be closing this issue as I am unable to recreate this issue on my end. Please open a support ticket on www.paidmembershipspro.com if you have any further questions.
