### ISSUE TITLE
Enhancement: Add support for the First and Last Name Fields

### ISSUE THREAD

**Issue by JarrydLong** [strangerstudios/pmpro-zapier#51]
This comes up quite often as users assume that once they use the Add Name to Checkout Add-on that the fields would automatically sent through to Zapier. Perhaps we can add those fields in be default and if the plugin isn't in use, the values just return empty.

**Comment by andrewlimaza** [comment]
Merged here - https://github.com/strangerstudios/pmpro-zapier/pull/62
