### ISSUE TITLE
Bug: Changing Membership Level via Webhook to Level 0 Results in Error

### ISSUE THREAD

**Issue by JarrydLong** [strangerstudios/pmpro-zapier#58]
- When cancelling a membership level by using the change membership level webhook option, we would typically set it to 0 to remove the level
- Currently, when doing so, we get the error "You must pass in valid level_id."
- We check for a string on https://github.com/strangerstudios/pmpro-zapier/blob/master/includes/webhook-handler.php#L102 where the $level_id is not an int. Changing that check seems to resolve the issue. 

Relates to https://www.paidmembershipspro.com/forums/topic/api-key-for-zapier-keeps-on-changing/ (mods only)

**Comment by dparker1005** [comment]
Just replicated for the `change_membership_level` webhook here:
https://github.com/strangerstudios/pmpro-zapier/blob/bce79c0cf9dc26bae84d498347277135c3ea3be8/includes/webhook-handler.php#L140-L143

Ticket (admins only): https://www.paidmembershipspro.com/forums/topic/zapier-for-removing-membership-level-revisit/

**Comment by dparker1005** [comment]
This should have been resolved in 1.1.1

**Comment by andrewlimaza** [comment]
Thanks! Closing this issue.
