### ISSUE TITLE
"order" field no longer being filled on "after checkout" trigger

### ISSUE THREAD

**Issue by dparker1005** [strangerstudios/pmpro-zapier#68]
In PMPro v2.9, the MemberOrder class was refactored to avoid warnings in PHP 8+. Part of this refactor was defining private properties for the class which can be accessed using a magic getter.

PMPro Zapier sends information about the MemberOrder by adding the entire order to the webhook request (`		$data['order'] = $order;`). The fact that order properties are now private is causing this approach to no longer work. Instead, we should change PMPro Zapier to send specific pieces of order information in the webhook request and use the magic getter to retrieve that information. This also has the added benefit of standardizing the order information that Zapier can expect to receive.

**Comment by gnpwdr-mike** [comment]
Hi @dparker1005 - I was the one that raised this issue over on your website's support forum.

Since it doesn't sound like there is an ETA for a resolution for this newly-introduced bug, I wanted to see if you would be able to provide some basic instructions for allowing us to pass order-related data to Zapier, ideally using the the `$order` parameter of the `pmproz_after_checkout_data` filter.

Inside my current function that uses the `pmproz_after_checkout_data` filter, I’ve consoled out the contents of `$order`, which you can see below, however, none of the contents make their way over to Zapier.

**Can we simply convert `$order`'s type from MemberOrder to some other JSON-like format, or remove the "private" aspect of the object for the time being?**

Thanks –

```php
(
    [id:MemberOrder:private] => 8
    [code:MemberOrder:private] => B3BC2AC799
    [user_id:MemberOrder:private] => 5
    [membership_id:MemberOrder:private] => 1
    [billing:MemberOrder:private] => stdClass Object
        (
            [name] => 
            [street] => 
            [city] => 
            [state] => 
            [zip] => 
            [country] => 
            [phone] => 
        )

    [subtotal:MemberOrder:private] => 1
    [tax:MemberOrder:private] => 0
    [couponamount:MemberOrder:private] => 
    [certificate_id:MemberOrder:private] => 0
    [certificateamount:MemberOrder:private] => 
    [total:MemberOrder:private] => 1
    [payment_type:MemberOrder:private] => Check
    [cardtype:MemberOrder:private] => 
    [accountnumber:MemberOrder:private] => 
    [expirationmonth:MemberOrder:private] => 
    [expirationyear:MemberOrder:private] => 
    [status:MemberOrder:private] => pending
    [gateway:MemberOrder:private] => check
    [gateway_environment:MemberOrder:private] => live
    [payment_transaction_id:MemberOrder:private] => CHECKB3BC2AC799
    [subscription_transaction_id:MemberOrder:private] => 
    [timestamp:MemberOrder:private] => 1659986307
    [affiliate_id:MemberOrder:private] => 
    [affiliate_subid:MemberOrder:private] => 
    [notes:MemberOrder:private] => 
    [checkout_id:MemberOrder:private] => 8
    [other_properties:MemberOrder:private] => Array
        (
            [original_status] => pending
            [membership_name] => Test Membership
            [discount_code] => 
            [InitialPayment] => 1
            [PaymentAmount] => 0
            [ProfileStartDate] => 2022-08-08T15:18:27
            [BillingPeriod] => 
            [BillingFrequency] => 0
            [CVV2] => 
            [Email] => test@testing.com
            [FirstName] => 
            [LastName] => 
            [Address1] => 
            [Address2] => 
            [membership_level] => stdClass Object
                (
                    [id] => 1
                    [name] => Test Membership
                    [description] => The initiation fee for this membership is <strong>$1</strong> now.
                    [confirmation] => 
                    [initial_payment] => 1
                    [billing_amount] => 0
                    [cycle_number] => 0
                    [cycle_period] => 
                    [billing_limit] => 0
                    [trial_amount] => 0
                    [trial_limit] => 0
                    [allow_signups] => 1
                    [expiration_number] => 1
                    [expiration_period] => Week
                )

            [initial_amount] => 1
            [subscription_amount] => 0
            [CardType] => 
            [datetime] => 2022-08-08 19:18:27
        )

)
```

**Comment by dparker1005** [comment]
Hi @gnpwdr-mike,

You should still be able to send specific pieces of order data to Zapier using the `$order` parameter of the `pmproz_after_checkout_data` filter by calling `$order->{property}`. There is now a magic `__get()` method in the MemberOrder class that should make all properties accessible.

For example, calling `$order->membership_id` should still work even though that property is technically private.

**Comment by andrewlimaza** [comment]
Just sharing this here, but another solution is to cast the object to an array when we add it to the $data variable that's being sent. 

For example: `$data['order'] = (array) $order;`

**Comment by gnpwdr-mike** [comment]
@dparker1005 @andrewlimaza Thanks both for the info! Casting the MemberOrder object to an array is a perfect workaround for the time being.
